language: julia

os:
  - linux

julia:
  - 1.1

after_success:
  - julia --inline=no -e 'using Pkg; Pkg.add("Coverage"); import TensorNetworks; joinpath(dirname(pathof(TensorNetworks))); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("DocumenterTools"); Pkg.add("Documenter"); ENV["DOCUMENTER_DEBUG"] = "true"; import TensorNetworks; joinpath(dirname(pathof(TensorNetworks))); include(joinpath("docs","make.jl"))'
