name = "TensorNetworks"
uuid = "814ffd40-6dfc-11e9-0e20-0f728e50871f"
authors = ["waltergu <waltergu1989@gmail.com>"]
version = "0.1.0"

[deps]
QuantumLattices = "78ae1a1f-1d5d-5174-b61c-66e31b2346dc"

[compat]
julia = "~1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
